version: '3.3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5434:5432

    environment:
      POSTGRES_DB: objectives-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
